import { ApiProperty } from '@nestjs/swagger';

export class TeamMemberPerformanceAnalyticsDto {
  @ApiProperty({
    description: 'Full name of the team member',
    example: 'John Doe',
  })
  full_name: string;

  @ApiProperty({
    description: 'Role of the team member',
    example: 'Sales Representative',
  })
  role: string;

  @ApiProperty({
    description: 'Total revenue generated by the team member',
    example: 50000,
  })
  total_revenue: number;

  @ApiProperty({
    description: 'Total clients handled by the team member',
    example: 100,
  })
  total_clients: number;

  // @ApiProperty({
  //   description: 'Clients with revenue generated by the team member',
  //   example: 80,
  // })
  // clients_with_revenue: number;

  @ApiProperty({
    description: 'Conversion rate of the team member',
    example: 0.8,
  })
  conversion_rate: number;

  constructor(data: {
    full_name: string;
    role: string | null;
    total_revenue: number;
    total_clients: number;
    // clients_with_revenue: number;
    conversion_rate: number;
  }) {
    const trimNamed = data.full_name.trim();
    this.full_name = trimNamed || 'Unknown';
    this.role = data.role ?? '-';
    this.total_revenue = data.total_revenue;
    this.total_clients = data.total_clients;
    // this.clients_with_revenue = data.clients_with_revenue;
    this.conversion_rate = data.conversion_rate;
  }
}
